version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "contactbook"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - pg-db-network
    restart: always

  contact-book-api:
    container_name: contact-book-api
    image: contact-book:latest
    environment:
      SERVER_PORT: 8090
      SPRING_PROFILES_ACTIVE: qa
      TZ: "America/Sao_Paulo"
      DB_USER: root
      DB_PWD: root
    ports:
        - "8087:8090"
    depends_on:
      - postgres-db
    networks:
        - pg-db-network
    restart: always

networks:
  pg-db-network:
    driver: bridge