version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "contactbook"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - docker-network
    restart: always

  contact-book-api:
    container_name: contact-book-api
    image: contact-book:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
      DB_USER: root
      DB_PWD: root
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M

networks:
  docker-network:
    driver: bridge