# Port config
server:
  port: 8080

# Spring config
spring:
  application:
    name: spring-cloud-config-server

  # Database config
  datasource:
    url: jdbc:postgres://localhost:5443/contactbook?currentSchema=public
    username: ${DB_USER} # Enter your username
    password: ${DB_PWD} # Enter your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Flyway config
  flyway:
    locations: db/migration
    baseline-on-migrate: true

  # Devtools config
  devtools:
    restart:
    enabled: true

# Swagger config
springdoc:
  swagger-ui:
    path: /contactbook/swagger-ui.html

# Viacep URL endpoint
viacep:
  url: https://viacep.com.br/ws/
