#port config
server:
  port: 8090

spring:
  application:
    name: "contactbook"
  config:
    activate:
      on-profile: qa

  #database config
  datasource:
    url: jdbc:postgresql://postgres-db:5432/contactbook?currentSchema=public
    username: root
    password: root
    driver-class-name: "org.postgresql.Driver"
    hikari:
      schema: public

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #flyway config
  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

#swagger config
springdoc:
  swagger-ui:
    path: "/contactbook/swagger-ui.html"

#viacep url endpoint
viacep:
  endpoint: "http://viacep.com.br/ws"


